### ISSUE TITLE
bs3-align was not running but no error appeared either

### ISSUE THREAD

**Issue by yupenghe** [khuang28jhu/bs3#1]
Hi,
I ran `./bs3/bs3-align.py -i FASTQ_FILE -g FASTA_FILE` but bs3 was not running and no error was reported. I cloned bs3 today (Apr 10). Any idea about this issue? Please let me know if you need more information. Thanks!

Yupeng

**Comment by khuang28jhu** [comment]
Is this single end read?

You should do something like

./bs3-align -i test_data/WGBS.fa -o WGBS -f sam -g reference_genome/genome.fa -d reference_genome/

where -d specifies where the index directory is. 

Also make sure you have the latest version, because I committed 19 hours ago.

**Comment by yupenghe** [comment]
Thanks. It works with adding `-d`, `-o` and `-f` options. Just a suggestion. It may be better to state the required options in the help information.
