### ISSUE TITLE
got a problem about bs-seeker3

### ISSUE THREAD

**Issue by feihongloveworld** [khuang28jhu/bs3#2]
Hi~ boy
      i want to use this soft . run align afte built index, but can not any message..
      just like the below:
#######################
python bs3-align.py \
    -1 VP_Liu_C1_RDML00187_BHCLCYCCXY_L1_1.clean.fq.gz \
    -2 VP_Liu_C1_RDML00187_BHCLCYCCXY_L1_2.clean.fq.gz \
    -g ucsc.hg19.fasta

     BS-Seeker3 beta

#######################
just got the message---BS-Seeker3 beta
what can i do for it  ????????????????????????????

**Comment by khuang28jhu** [comment]
Sample command:

./bs3-align -1 test_data/pair1.fq -2 test_data/pair2.fq -o WGBC -f sam -g reference_genome/genome.fa **-d reference_genome/**

**Comment by DarrellL** [comment]
Hi, I'm coming up with this same error, both with my data and when running your sample command. The bs3-build step completed succesfully

./bs3-align -1 test_data/pair1.fq -2 test_data/pair2.fq -o WGBC -f sam -g reference_genome/genome.fa -d reference_genome/

     BS-Seeker3 beta

Is this software still being supported? I note that Bs_seeker2 has been updated more recently.
