### ISSUE TITLE
sched_setaffinity: Invalid argument

### ISSUE THREAD

**Issue by keroguynes** [khuang28jhu/bs3#33]
<img width="623" alt="Screenshot 2020-03-19 at 20 05 35" src="https://user-images.githubusercontent.com/55197160/77110244-2bd1ff80-6a1d-11ea-965f-de62e926c490.png">

I simply cannot seem to resolve this. Does anyone know how to trouble shoot this issue?
I have tried increasing the number of thread and cores but still nothing unfortunately.

**Comment by chaseleif** [comment]
Look at line 263 of bs3/bs3-align.py. There is a hard-coded number of threads in the program parameters of 32. I remember having this issue and, from what I found from others, it doesn't affect the results. I got rid of the warning by lowering the number to 8.
(note: I am just a coder and used BS3 for a project a year ago)
